FROM python:3.11-slim

# Cài các gói cần thiết
RUN apt-get update && apt-get install -y build-essential libffi-dev python3-dev git && rm -rf /var/lib/apt/lists/*

# Copy project và requirements
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy code
COPY . /app

# Mở port (nếu Railway cần)
EXPOSE 5000

# Chạy app
CMD ["python", "main.py"]
