FROM python:3.11-slim

# Cài các gói cần thiết để tạo venv
RUN apt-get update && apt-get install -y python3-venv build-essential && rm -rf /var/lib/apt/lists/*

# Tạo venv
RUN python -m venv /opt/venv
# Copy requirements và cài
COPY requirements.txt .
RUN /opt/venv/bin/pip install --upgrade pip
RUN /opt/venv/bin/pip install -r requirements.txt

# Thêm thư mục app
WORKDIR /app
COPY . /app

# Chạy app
CMD ["/opt/venv/bin/python", "main.py"]
